### ISSUE TITLE
Output in Kallisto-quant not working

### ISSUE THREAD

**Issue by Brilator** [common-workflow-library/bio-cwl-tools#156]
Hi, I've tested the [Kallisto-Quant.cwl](https://github.com/common-workflow-library/bio-cwl-tools/blob/release/Kallisto/Kallisto-Quant.cwl) with 

```yaml
InputReads:
    - class: File
      path: ../../rnaseq/sample1-1.fastq.gz
    - class: File
      path: ../../rnaseq/sample1-2.fastq.gz
Index:
  class: File
  path: ../../kallisto-index-biocwl/output/Fbid
isSingle: true  
FragmentLength: 200
StandardDeviation: 20  
BootstrapSamples: 0
PseudoBam: false
```

Unfortunately the output is not wired properly. 

```
("Error collecting output for parameter 'quantification_h5': Kallisto-Quant.cwl:129:7: Did not find output file with glob pattern: ['out/abundances.h5'].", {})
```

I am new to CWL, so not sure how to fix and PR.

**Comment by Brilator** [comment]
Also, for the fusions output (l 146), it should probably say       `glob: "out/fusion.txt"` instead of       `glob: "fusion.txt"`

**Comment by mr-c** [comment]
Thank you @Brilator for reporting this!

If you are running with `cwltool`, try `cwtool --cachedir cache Kallisto-Quant.cwl my_inputs.yml` or similar, then check the directory `cache` and there will be all the files; maybe that will help you suggest a better `glob` line for `quantification_h5`

**Comment by Brilator** [comment]
Thanks, I did that. 

For me, adding another input string for the output folder and completely yielding that as output worked. 

```yaml
  QuantOutfolder: 
    type: string

outputs:

#   quantification_h5:
#     type: File
#     outputBinding:
#       glob: out/abundances.h5

# # Long form method for defining optional outputs

#   quantification_tsv:
#     type: File
#     outputBinding:
#       glob: out/abundances.tsv

#   bam:
#     type: ["null", File]
#     outputBinding:
#       glob: "out/*.bam"

#   fusions:
#     type: ["null", File]
#     outputBinding:
#       glob: "fusion.txt"

  outFolder:
    type: Directory
    outputBinding:
      glob: $(runtime.outdir)/$(inputs.QuantOutfolder)
```
